version: "3.8"
services:
  nginx-container:
    container_name: nginx-container
    image: garseb/m300nginx
    hostname: nginx-container
    restart: always
    ports:
      - 80:80

  redis-container:
    container_name: redis-server
    image: redis
    hostname: redis-container
    restart: always
    ports:
      - 6379:6379

  api-server:
    container_name: api-server
    depends_on:
      - redis-container
    image: garseb/m300node
    restart: always
    ports:
      - 3001:3001
      - 3000:3000
    environment:
      API_PORT: 3001
      SOCKETIO_SERVER_PORT: 3000
      REDIS_IP: redis-container
      REDIS_PORT: 6379
      CORS_SOURCE_PROTOCOL: http
      CORS_SOURCE_DOMAIN: 127.0.0.1
      CORS_SOURCE_PORT: 80