apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: m300nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: arduino-node-service-tcp-80
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: tcp-80
      port: 80
      targetPort: 80