apiVersion: apps/v1   
kind: Deployment
metadata:
  name: arduino-redis-deployment
  labels:
    app: arduino-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arduino-redis
  template:
    metadata:
      labels:
        app: arduino-redis
    spec:
      containers:
      - name: arduino-redis-container
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: arduino-redis-service
spec:
  type: LoadBalancer
  selector:
    app: arduino-redis
  ports:
    - protocol: TCP
      name: tcp-6379
      port: 6379
      targetPort: 6379